config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'screens#index'

  resources :users
  resources :screens do
    collection do
      get "/:id/slideshow" => "screens#slideshow", as: "slideshow"
    end

    resources :images, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/screen.rb
class Screen < ApplicationRecord
  belongs_to :user

  mount_uploaders :images, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :screens
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_screen

  def create
    add_more_images(images_params[:images])
    flash[:error] = "Failed uploading images" unless @screen.save
    redirect_to @screen
  end

  def destroy
    remove_image_at_index(params[:id].to_i)
    flash[:error] = "Failed deleting image" unless @screen.save
    redirect_to @screen
  end

  private

  def set_screen
    @screen = Screen.find(params[:screen_id])
  end

  def add_more_images(new_images)
    images = @screen.images
    images += new_images
    @screen.images = images
  end

  def remove_image_at_index(index)
    remain_images = @screen.images
    deleted_image = remain_images.delete_at(index)
    deleted_image.try(:remove!)
    remain_images.empty? ? @screen.update_column(:images, nil) : @screen.images = remain_images
    @screen.save
  end

  def images_params
    params.require(:screen).permit({images: []})
  end
end

app/controllers/screens_controller.rb
class ScreensController < ApplicationController
  before_action :set_screen, only: [:show, :edit, :update, :destroy, :slideshow]
  before_action :authenticate_user!, except: [:slideshow]

  def index
    @screens = Screen.all
  end

  def show
  end

  def new
    @screen = Screen.new
  end

  def edit
  end

  def create
    @screen = Screen.new(screen_params)
    @screen.user = current_user

    respond_to do |format|
      if @screen.save
        format.html { redirect_to @screen, notice: 'Screen was successfully created.' }
        format.json { render :show, status: :created, location: @screen }
      else
        format.html { render :new }
        format.json { render json: @screen.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @screen.name     = screen_params[:name]
    @screen.interval = screen_params[:interval]

    if screen_params[:images]
      images = @screen.images
      images += screen_params[:images]
      @screen.images = images
    end

    respond_to do |format|
      if @screen.save
        format.html { redirect_to @screen, notice: 'Screen was successfully updated.' }
        format.json { render :show, status: :ok, location: @screen }
      else
        format.html { render :edit }
        format.json { render json: @screen.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @screen.destroy
    respond_to do |format|
      format.html { redirect_to screens_url, notice: 'Screen was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def slideshow
  end

  private
    def set_screen
      @screen = Screen.find(params[:id])
    end

    def screen_params
      params.require(:screen).permit(:name, :interval, :user_id, images: [])
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def date_string_for(datetime)
    datetime.strftime('%m/%d/%Y %H:%M:%S')
  end

  def link_to_image(image_path, target_link, options={})
    link_to(image_tag(image_path, height: '90', width: '130'), target_link, options)
  end
end

app/helpers/screens_helper.rb
module ScreensHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <div class="col-sm-12 text-center navbar-text">
      version <%= ::VERSION %>
    </div>
  </div>
</nav>

app/views/layouts/_topnav.html.erb
<% if current_user %>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Digital Menu Board</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'New', new_screen_path %></li>
            <li><%= link_to 'Screens', screens_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown-user">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#"><%= link_to '<i class="fa fa-sign-out fa-fw"></i> Logout'.html_safe, destroy_user_session_path, method: :delete %></a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DigitalMenuBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% unless controller.action_name == 'slideshow' %>
      <div id="wrapper">
        <div class="container">
          <%= render 'layouts/topnav' %>
          <%= yield %>
        </div>
        <%= render 'layouts/footer' %>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/screens/_form.html.erb
<%= form_with(model: screen, local: true) do |form| %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :screen_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :interval %>
    <%= form.number_field :interval, value: 20, id: :screen_name, class: 'form-control' %>
  </div>

  <%= form.label :images %>
  <% if screen %>
    <% screen.images.each_with_index do |image, index| %>
      <div class="form-group">
        <%= image_tag image.url, height: '180', width: '260' %>
        <%= link_to "Delete", screen_image_path(screen, index), :method => :delete, data: { confirm: "Are you sure you want to delete this image?" } %>
      </div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= form.file_field :images, multiple: true, accept: "image/jpeg, image/jpg, image/gif, image/png, image/svg" %>
  </div>

  <div class="form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/screens/edit.html.erb
<h1>Editing Screen</h1>

<%= render 'form', screen: @screen %>

<%= link_to 'Back', screens_path %>

app/views/screens/index.html.erb
<h1>Screens</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th style="width: 15%">Slideshow</th>
      <th style="width: 15%">Name</th>
      <th style="width: 15%">Number of images</th>
      <th style="width: 15%">Interval</th>
      <th style="width: 25%">Updated at</th>
    </tr>
  </thead>

  <tbody>
    <% @screens.each do |screen| %>
      <tr>
        <td><%= link_to_image(screen.images.first.url, slideshow_screens_path(screen)) if screen.images.first %></td>
        <td><%= link_to screen.name, screen_path(screen) %></td>
        <td><%= screen.images.count %></td>
        <td><%= "#{screen.interval} seconds" %></td>
        <td><%= date_string_for(screen.updated_at) %></td>
        <td><%= link_to 'Edit', edit_screen_path(screen) %></td>
        <td><%= link_to 'Destroy', screen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Screen', new_screen_path, class: 'btn btn-primary' %>

app/views/screens/new.html.erb
<h1>New Screen</h1>

<%= render 'form', screen: @screen %>

<%= link_to 'Back', screens_path %>

app/views/screens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @screen.name %>
</p>

<p>
  <strong>Interval:</strong>
  <%= @screen.interval %>
</p>

<p>
  <strong>User:</strong>
  <%= @screen.user.email %>
</p>

<p>
  <strong>Images:</strong>
</p>

<% @screen.images.each do |image| %>
  <p>
    <%= image_tag image.url, height: '200', width: '290' %>
  </p>
<% end %>

<%= link_to 'Edit', edit_screen_path(@screen) %> |
<%= link_to 'Slideshow', slideshow_screens_path(@screen) if @screen.images.first %> |
<%= link_to 'Back', screens_path %>

app/views/screens/slideshow.html.erb
<div id = "myCarousel" class = "carousel slide" data-ride="carousel" >
  <div class="carousel-inner img">
    <div class="item active">
      <%= image_tag @screen.images.first.url %>
    </div>
    <% @screen.images.drop(1).each do |photo| %>
        <div class="item">
          <%= image_tag photo.url, :size => '100X100' %>
        </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('#myCarousel').carousel({
      interval: 1000 * <%= @screen.interval.to_int %>
    });
  });
</script>

<style type="text/css">
  html { height: 100% }
  body { height: 100%; margin: 0; padding: 0 }
</style>